# -*- coding: utf-8 -*-
"""UCD_Aline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HvIe-e8LXsCiDRtn84KlZaxhvpLY13jy
"""

# import data
import pandas as pd
df = pd.read_csv('uk_air_passengers.csv', sep=';')
print('UK Air Passengers :')
print(df.iloc[0:5])

df['datetime']=pd.to_datetime(df['Date'])



df=df.drop_duplicates(subset=['datetime'])
print(len(df))

df=df.dropna()
print(df.shape)

df=df.set_index('datetime')

# 1. What is the average number of passengers per month?
avg_passengers_per_day = round(df['Passengers'].mean())
print('The average number of passengers per day is', avg_passengers_per_day)

# 2. Plot the number of monthly passengers?
import matplotlib.pyplot as plt
plt.plot(df.index, df['Passengers'])
plt.xlabel('Date')
plt.ylabel('Number of Passengers')
plt.title('Q2: Number of monthly passengers')
plt.show()

df[df['Passengers']<4000000]

x=df['Passengers'].min()
df.loc[df['Passengers'] == x]

# 3. Plot the number of yearly passengers?
df_grouped = df.groupby('year')
df_mean = df_grouped.mean('Passengers')
df_mean.plot(kind='line', y='Passengers')
plt.title('Q3: Number of yearly passengers')
plt.show()

# 4. Rank the months by the number of passengers (Bar Chart)
df_grouped = df.groupby('month')
df_mean = df_grouped.mean('Passengers')
df_sorted = df_mean.sort_values(by='Passengers', ascending=False)
df_sorted.plot(kind='bar', y='Passengers')
plt.title('Q4: Most Popular Months')
plt.show()

# 5. Percentage of Passengers to fly by Year (Pie Chart)
df_grouped = df.groupby('year').sum()
plt.pie(df_grouped['Passengers'], labels=df_grouped.index, autopct='%1.1f%%')
plt.title('Percentage of Passengers to fly by Year')
plt.show()

# 6. Display the 3 months with the highest number of passengers
df_grouped = df.groupby('month')
df_mean = df_grouped.mean('Passengers')
df_sorted = round(df_mean.sort_values(by='Passengers', ascending=False),)
print('The 3 months with the highest number of passengers are: ')
print(df_sorted.head(3))

# 7. Display the 3 months with the lowest number of passengers
df_grouped = df.groupby('month')
df_mean = df_grouped.mean('Passengers')
df_sorted = round(df_mean.sort_values(by='Passengers', ascending=True),)
print('The 3 months with the lowest number of passengers are: ')
print(df_sorted.head(3))

"""# Covid Data"""

def get_covid_data():
  response=requests.get('https://api.coronavirus.data.gov.uk/v1/data')
  data=response.json()
  return data

import requests
data = get_covid_data()

# Convert list of dictionaries to DateFrame
df_covid=pd.DataFrame(data['data'])
df_covid.tail()

# Using NumPy to check for Null values
len(df_covid['confirmedRate'].isnull())

df_covid=df_covid[['date','latestBy']]
df_covid['datetime']=pd.to_datetime(df_covid['date'])
df_covid=df_covid.set_index('datetime')
df_covid=df_covid.groupby(pd.Grouper(freq='MS')).mean()
df_covid

# Removing Null Vales'NaN'
df_covid=round(df_covid.dropna(),)
df_covid

import seaborn as sns
sns.lineplot(data=df_covid)

df_merged=pd.merge(df,df_covid,on='datetime')[['Passengers','latestBy']]
df_merged

# sns.lineplot(data=df_merged)
import matplotlib.pyplot as plt
sns.lineplot(data=df_merged['latestBy'], color="g")
ax2 = plt.twinx()
sns.lineplot(data=df_merged['Passengers'], color="b", ax=ax2)

for i, row in enumerate(df_merged.itertuples(), 1):
    print(f'flights: {row.Passengers} Covid Cases: {row.latestBy}')

